build:
    environment:
        php:
            version: 7.0.10
    tests:
        override:
            -
                command: phpunit --coverage-clover=clover.xml
                coverage:
                    file: clover.xml
                    format: php-clover
