build:
    environment:
        php:
            version: 7.0.10
    tests:
        override:
            -
                command: phpunit --coverage-clover=coverage.clover
                coverage:
                    file: coverage.clover
                    format: php-clover
